// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/transactions": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/plans": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/invoice": {
    params: {};
  };
  "/otp": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/create-account": {
    params: {};
  };
  "/verify-otp": {
    params: {};
  };
  "/logistics": {
    params: {};
  };
  "/logistics/delivery": {
    params: {};
  };
  "/logistics/login": {
    params: {};
  };
  "/vendor": {
    params: {};
  };
  "/vendor/login": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/transactions" | "/orders" | "/plans" | "/settings" | "/invoice" | "/otp" | "/login" | "/create-account" | "/verify-otp" | "/logistics" | "/logistics/delivery" | "/logistics/login" | "/vendor" | "/vendor/login" | "/admin" | "/admin/login";
  };
  "portals/customer/CustomerLayout.tsx": {
    id: "portals/customer/CustomerLayout";
    page: "/" | "/transactions" | "/orders" | "/plans" | "/settings" | "/invoice" | "/otp";
  };
  "portals/customer/pages/Home.tsx": {
    id: "portals/customer/pages/Home";
    page: "/";
  };
  "portals/customer/pages/Transactions.tsx": {
    id: "portals/customer/pages/Transactions";
    page: "/transactions";
  };
  "portals/customer/pages/Orders.tsx": {
    id: "portals/customer/pages/Orders";
    page: "/orders";
  };
  "portals/customer/pages/Plans.tsx": {
    id: "portals/customer/pages/Plans";
    page: "/plans";
  };
  "portals/customer/pages/Settings.tsx": {
    id: "portals/customer/pages/Settings";
    page: "/settings";
  };
  "portals/customer/pages/Invoice.tsx": {
    id: "portals/customer/pages/Invoice";
    page: "/invoice";
  };
  "portals/customer/pages/OtpFlow.tsx": {
    id: "portals/customer/pages/OtpFlow";
    page: "/otp";
  };
  "portals/customer/pages/Login.tsx": {
    id: "portals/customer/pages/Login";
    page: "/login";
  };
  "portals/customer/pages/CreateAccount.tsx": {
    id: "portals/customer/pages/CreateAccount";
    page: "/create-account";
  };
  "portals/customer/pages/VerifyOtp.tsx": {
    id: "portals/customer/pages/VerifyOtp";
    page: "/verify-otp";
  };
  "portals/logistics/LogisticsLayout.tsx": {
    id: "portals/logistics/LogisticsLayout";
    page: "/logistics" | "/logistics/delivery";
  };
  "portals/logistics/pages/Home.tsx": {
    id: "portals/logistics/pages/Home";
    page: "/logistics";
  };
  "portals/logistics/pages/Delivery.tsx": {
    id: "logistics-delivery";
    page: "/logistics/delivery";
  };
  "portals/logistics/pages/Login.tsx": {
    id: "portals/logistics/pages/Login";
    page: "/logistics/login";
  };
  "portals/vendor/VendorLayout.tsx": {
    id: "portals/vendor/VendorLayout";
    page: "/vendor";
  };
  "portals/vendor/pages/Home.tsx": {
    id: "portals/vendor/pages/Home";
    page: "/vendor";
  };
  "portals/vendor/pages/Login.tsx": {
    id: "portals/vendor/pages/Login";
    page: "/vendor/login";
  };
  "portals/admin/AdminLayout.tsx": {
    id: "portals/admin/AdminLayout";
    page: "/admin";
  };
  "portals/admin/pages/Home.tsx": {
    id: "portals/admin/pages/Home";
    page: "/admin";
  };
  "portals/admin/pages/Login.tsx": {
    id: "portals/admin/pages/Login";
    page: "/admin/login";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "portals/customer/CustomerLayout": typeof import("./src/portals/customer/CustomerLayout.tsx");
  "portals/customer/pages/Home": typeof import("./src/portals/customer/pages/Home.tsx");
  "portals/customer/pages/Transactions": typeof import("./src/portals/customer/pages/Transactions.tsx");
  "portals/customer/pages/Orders": typeof import("./src/portals/customer/pages/Orders.tsx");
  "portals/customer/pages/Plans": typeof import("./src/portals/customer/pages/Plans.tsx");
  "portals/customer/pages/Settings": typeof import("./src/portals/customer/pages/Settings.tsx");
  "portals/customer/pages/Invoice": typeof import("./src/portals/customer/pages/Invoice.tsx");
  "portals/customer/pages/OtpFlow": typeof import("./src/portals/customer/pages/OtpFlow.tsx");
  "portals/customer/pages/Login": typeof import("./src/portals/customer/pages/Login.tsx");
  "portals/customer/pages/CreateAccount": typeof import("./src/portals/customer/pages/CreateAccount.tsx");
  "portals/customer/pages/VerifyOtp": typeof import("./src/portals/customer/pages/VerifyOtp.tsx");
  "portals/logistics/LogisticsLayout": typeof import("./src/portals/logistics/LogisticsLayout.tsx");
  "portals/logistics/pages/Home": typeof import("./src/portals/logistics/pages/Home.tsx");
  "logistics-delivery": typeof import("./src/portals/logistics/pages/Delivery.tsx");
  "portals/logistics/pages/Login": typeof import("./src/portals/logistics/pages/Login.tsx");
  "portals/vendor/VendorLayout": typeof import("./src/portals/vendor/VendorLayout.tsx");
  "portals/vendor/pages/Home": typeof import("./src/portals/vendor/pages/Home.tsx");
  "portals/vendor/pages/Login": typeof import("./src/portals/vendor/pages/Login.tsx");
  "portals/admin/AdminLayout": typeof import("./src/portals/admin/AdminLayout.tsx");
  "portals/admin/pages/Home": typeof import("./src/portals/admin/pages/Home.tsx");
  "portals/admin/pages/Login": typeof import("./src/portals/admin/pages/Login.tsx");
};