-- Referral codes are generated by the database so they are present for every profile.
create or replace function public.assign_referral_code()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate text;
begin
  if tg_op = 'UPDATE' and old.referral_code is not null
    and new.referral_code is distinct from old.referral_code then
    raise exception 'Referral codes cannot be changed';
  end if;

  if new.referral_code is null or btrim(new.referral_code) = '' then
    loop
      candidate := 'QF' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
      exit when not exists (select 1 from public.profiles where referral_code = candidate);
    end loop;
    new.referral_code := candidate;
  else
    new.referral_code := upper(btrim(new.referral_code));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_assign_referral_code on public.profiles;
create trigger trg_assign_referral_code
before insert or update of referral_code on public.profiles
for each row execute function public.assign_referral_code();

update public.profiles
set referral_code = null
where referral_code is null or btrim(referral_code) = '';

alter table public.profiles
  alter column referral_code set not null;

-- Customer clients may not attach or change referral attribution directly.
-- Trusted server code enables this setting only inside its transaction.
create or replace function public.protect_referral_attribution()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' and new.referred_by is not null
    and current_setting('qaffy.referral_attribution', true) <> 'true' then
    raise exception 'Referral attribution must use the trusted server path';
  end if;

  if tg_op = 'UPDATE' and old.referred_by is not null
    and new.referred_by is distinct from old.referred_by then
    raise exception 'Referral attribution cannot be changed';
  end if;

  if tg_op = 'UPDATE' and old.referred_by is null and new.referred_by is not null
    and current_setting('qaffy.referral_attribution', true) <> 'true' then
    raise exception 'Referral attribution must use the trusted server path';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_protect_referral_attribution on public.profiles;
create trigger trg_protect_referral_attribution
before insert or update of referred_by on public.profiles
for each row execute function public.protect_referral_attribution();

alter table public.referrals
  add column if not exists attributed_at timestamptz not null default now();